'use strict';let csrf='';const message=document.getElementById('admin-message');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify({...body,csrf})}:{})});if(r.status===401||r.status===403){location.assign('entrar.html');throw Error('Acesso restrito.');}const j=await r.json();if(!r.ok)throw Error(j.error);return j;}
async function load(){const j=await api('api/admin/students');document.getElementById('students').innerHTML=j.students.map(s=>`<article class="student"><strong>${esc(s.name)}</strong><p>${esc(s.email)} · ${s.active?'Ativo':'Suspenso'} · ${esc(JSON.parse(s.courses).join(', '))}</p><button data-toggle="${s.id}" data-active="${s.active}" data-courses="${esc(s.courses)}">${s.active?'Suspender':'Reativar'}</button><button data-reset="${s.id}">Recuperar acesso</button></article>`).join('')||'<p>Nenhum aluno cadastrado.</p>';document.getElementById('invitations').innerHTML=j.invitations.map(i=>`<article class="student"><strong>${esc(i.name)}</strong><p>${esc(i.email)} · Expira em ${new Date(i.expires*1000).toLocaleString('pt-BR')}</p></article>`).join('')||'<p>Nenhum convite pendente.</p>';}
document.getElementById('invite-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;message.textContent='';try{const f=new FormData(e.currentTarget),j=await api('api/admin/invite','POST',{name:f.get('name'),email:f.get('email'),courses:f.getAll('courses')});const out=document.getElementById('invite-output');out.textContent=(j.sent?'Convite enviado por e-mail.':'Envie este link exclusivamente ao aluno informado.')+' Válido por 48 horas.';const area=document.createElement('textarea');area.readOnly=true;area.value=j.link;area.setAttribute('aria-label','Link de convite');out.append(area);await load();await loadAdminSkills();}catch(err){message.textContent=err.message;}finally{b.disabled=false;}};
document.getElementById('students').onclick=async e=>{const b=e.target.closest('button');if(!b)return;b.disabled=true;try{if(b.dataset.toggle){await api('api/admin/student','PUT',{id:Number(b.dataset.toggle),active:b.dataset.active!=='1',courses:JSON.parse(b.dataset.courses)});await load();}else{const j=await api('api/admin/reset-link','POST',{id:Number(b.dataset.reset)});message.textContent='Envie ao aluno o link de recuperação, válido por 30 minutos: '+j.link;}}catch(err){message.textContent=err.message;}finally{b.disabled=false;}};
document.getElementById('logout').onclick=async()=>{await api('api/logout','POST',{});location.assign('entrar.html');};

let adminSkills=[];
const skillForm=document.getElementById('skill-form'),skillMessage=document.getElementById('skill-message');
let adminSkillLimit=60;
function renderAdminSkills(){const term=document.getElementById('admin-skill-search').value.toLocaleLowerCase('pt-BR');const filtered=adminSkills.filter(s=>[s.title,s.category,s.description].join(' ').toLocaleLowerCase('pt-BR').includes(term));document.getElementById('admin-skills').innerHTML=filtered.slice(0,adminSkillLimit).map(s=>`<article class="student"><strong>${esc(s.title)}</strong><p>${esc(s.category)} · ${esc(s.platform)} · v${esc(s.version)} · ${s.published?'Publicado para os alunos':'Rascunho'}</p><button data-skill-edit="${s.id}">Editar</button> <button data-skill-toggle="${s.id}">${s.published?'Retirar da biblioteca':'Publicar'}</button></article>`).join('')||'<p>Nenhuma skill cadastrada. Comece pelo formulário acima.</p>';
document.getElementById('admin-skill-count').textContent=`${filtered.length} skills · exibindo ${Math.min(filtered.length,adminSkillLimit)}`;document.getElementById('admin-skills-more').hidden=filtered.length<=adminSkillLimit;}
async function loadAdminSkills(){const j=await api('api/admin/skills');adminSkills=j.skills;renderAdminSkills();}
document.getElementById('admin-skill-search').oninput=()=>{adminSkillLimit=60;renderAdminSkills();};
document.getElementById('admin-skills-more').onclick=()=>{adminSkillLimit+=60;renderAdminSkills();};
function resetSkill(){skillForm.reset();skillForm.elements.id.value='';skillMessage.textContent='';}
document.getElementById('skill-new').onclick=resetSkill;
skillForm.onsubmit=async e=>{e.preventDefault();const b=skillForm.querySelector('[type=submit]');b.disabled=true;skillMessage.textContent='';try{const f=new FormData(skillForm),data=Object.fromEntries(f);data.published=skillForm.elements.published.checked;if(data.id)data.id=Number(data.id);else delete data.id;await api('api/admin/skills',data.id?'PUT':'POST',data);resetSkill();await loadAdminSkills();skillMessage.textContent='Skill salva. As publicadas já ficam disponíveis aos alunos.';}catch(err){skillMessage.textContent=err.message;}finally{b.disabled=false;}};
document.getElementById('admin-skills').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const s=adminSkills.find(s=>s.id===Number(b.dataset.skillEdit||b.dataset.skillToggle));if(!s)return;if(b.dataset.skillEdit){for(const [k,v] of Object.entries(s)){const field=skillForm.elements.namedItem(k);if(field){if(k==='published')field.checked=v;else field.value=v;}}skillMessage.textContent='Editando '+s.title;skillForm.scrollIntoView({behavior:'smooth',block:'start'});skillForm.elements.title.focus();return;}b.disabled=true;try{await api('api/admin/skills','PUT',{...s,published:!s.published});await loadAdminSkills();skillMessage.textContent=s.published?'Skill retirada da biblioteca.':'Skill publicada para todos os alunos.';}catch(err){skillMessage.textContent=err.message;b.disabled=false;}};

(async()=>{try{const s=await api('api/session');if(!s.authenticated||s.user.role!=='admin'){location.assign('entrar.html');return;}csrf=s.csrf;await load();await loadAdminSkills();await loadPayments();}catch(err){message.textContent=err.message;}})();


async function loadOrders(){const j=await api('/api/admin/payments/orders');document.getElementById('payment-orders').innerHTML=j.orders.map(o=>`<article class="student"><strong>${esc(o.name)} · ${esc(o.course==='admin_test'?'Teste administrativo':(o.course==='basica'?'Básico':'Avançado'))}</strong><p>${esc(o.email)} · ${(o.amount/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · ${esc(o.state)} · ${o.environment==='production'?'Venda real':'Teste'} · ${o.fulfilled==='1'||o.fulfilled===1?'Acesso liberado':'Acesso não liberado'}</p><small>${new Date(o.created*1000).toLocaleString('pt-BR')} · ${esc(o.reference_id)}</small></article>`).join('')||'<p>Nenhum pedido ainda.</p>';}
async function loadPayments(){const j=await api('/api/admin/payments/settings'),f=document.getElementById('payment-settings');f.elements.environment.value=j.environment;f.elements.enabled.checked=j.enabled;document.getElementById('payment-connection').textContent=j.configured?`Token salvo · ${j.environment==='production'?'Produção':'Sandbox'} · ${j.enabled?'Novas matrículas habilitadas':'Novas matrículas desabilitadas'}`:'Conta PagBank ainda não conectada.';const d=j.diagnostic;if(d)document.getElementById('payment-settings-message').textContent='Última resposta do PagBank: HTTP '+d.http_status+(d.codes.length?' · '+d.codes.join(', '):'')+(d.parameters.length?' · campos: '+d.parameters.join(', '):'');await loadOrders();}
document.getElementById('payment-settings').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),m=document.getElementById('payment-settings-message');b.disabled=true;m.textContent='';try{await api('/api/admin/payments/settings','PUT',{environment:f.elements.environment.value,token:f.elements.token.value,enabled:f.elements.enabled.checked});f.elements.token.value='';await loadPayments();m.textContent='Configuração salva. Confira uma compra de teste e o webhook antes de divulgar.';}catch(err){m.textContent=err.message;}finally{b.disabled=false;}};
document.getElementById('refresh-orders').onclick=async()=>{try{await loadOrders();}catch(err){document.getElementById('payment-settings-message').textContent=err.message;}};
