'use strict';
(() => {
  const preview=document.documentElement.dataset.preview==='true';
  const main=document.getElementById('student-main');
  let catalog,completed=new Set(),csrf='',storageAvailable=true,lastLesson='ia-generativa';
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const allLessons=()=>catalog.courses.flatMap(c=>c.modules.flatMap(m=>m.lessons));
  const pilots=()=>allLessons().filter(l=>l.available);
  const notice=message=>{const node=document.getElementById('notice');node.textContent=message;clearTimeout(notice.timer);notice.timer=setTimeout(()=>node.textContent='',4500);};
  async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify({...body,csrf})}:{})});if(response.status===401){location.assign('entrar.html');throw new Error('Sua sessão expirou.');}let data;try{data=await response.json();}catch{location.assign('entrar.html');throw new Error('Acesso aguardando ativação.');}if(!response.ok)throw new Error(data.error||'Não foi possível salvar.');return data;}
  function courseRows(){return catalog.courses.map(c=>`<article class="course-row"><div><h3>${escape(c.name)}</h3><p>${escape(c.description)}</p></div><div class="course-status">${escape(c.status)}</div><a class="text-link" href="#curso/${c.id}">Explorar jornada <span aria-hidden="true">→</span></a></article>`).join('');}
  function overview(){const lesson=pilots().find(l=>l.id===lastLesson&&!completed.has(l.id))||pilots().find(l=>!completed.has(l.id))||pilots()[0];return `<h1>Seu próximo passo começa aqui.</h1><p class="lede">Aprenda, construa e aplique no seu trabalho.</p><section class="continue"><div><span class="kicker">CADERNO DE AULA · JORNADA ESCRITA</span><h2>${escape(lesson.title)}</h2><p>Leia, pratique e registre sua entrega.</p><a class="button" href="#aula/${lesson.id}">Abrir aula <span aria-hidden="true">→</span></a></div><span class="big-number" aria-hidden="true">${String(pilots().indexOf(lesson)+1).padStart(2,'0')}</span></section><section><h2>Suas formações</h2>${courseRows()}</section><section class="library-strip"><div><h2>Biblioteca prática</h2><p>Roteiros e materiais para construir junto.</p></div><a href="#materiais" class="text-link">Ver materiais <span aria-hidden="true">→</span></a></section>`;}
  function course(id){const c=catalog.courses.find(c=>c.id===id);if(!c)return empty('Curso não encontrado.');const ready=c.modules.flatMap(m=>m.lessons).filter(l=>l.available);return `<a class="back-link" href="#cursos">← Meus cursos</a><h1>${escape(c.name)}</h1><p class="lede">${escape(c.description)}</p><p class="note">${c.hours} horas ao vivo pelo Google Meet · ${ready.length} cadernos de aula disponíveis. Videoaulas em preparação. <a class="text-link" href="planos.html#${c.id}">Ver planejamento completo →</a></p>${c.modules.map((m,i)=>`<details class="module" ${i===0?'open':''}><summary>${escape(m.name)}</summary>${m.lessons.map(l=>`<div class="lesson-row"><div>${escape(l.title)}<small>${completed.has(l.id)?'Concluída':l.available?'Caderno de aula · vídeo em preparação':'Em preparação'}</small></div>${l.available?`<a class="text-link" href="#aula/${l.id}">Abrir aula →</a>`:'<span class="note">Em breve</span>'}</div>`).join('')}</details>`).join('')}`;}
  const empty=text=>`<h1>${escape(text)}</h1><a class="text-link" href="#visao">Voltar à visão geral</a>`;
  function lesson(id){const l=allLessons().find(l=>l.id===id&&l.available);if(!l)return empty('Esta aula ainda não está disponível.');lastLesson=id;if(preview){try{localStorage.setItem('lf-preview-last',id);}catch{storageAvailable=false;}}const owner=catalog.courses.find(c=>c.modules.some(m=>m.lessons.some(x=>x.id===id)));const sequence=owner.modules.flatMap(m=>m.lessons).filter(x=>x.available);const index=sequence.indexOf(l),next=sequence[index+1];return `<a class="back-link" href="#curso/${owner.id}">← ${escape(owner.name)}</a><h1>${escape(l.title)}</h1><p class="lede">Caderno escrito · módulo ao vivo pelo Google Meet · ${l.duration} min</p><div class="lesson-layout"><article class="lesson-content">${l.sections.map(s=>`<section><h2>${escape(s.title)}</h2>${s.text?`<p>${escape(s.text)}</p>`:''}${s.steps?`<ol>${s.steps.map(t=>`<li>${escape(t)}</li>`).join('')}</ol>`:''}</section>`).join('')}<div class="completion-actions"><button class="button" data-complete="${id}" aria-pressed="${completed.has(id)}">${completed.has(id)?'Desmarcar conclusão':'Marcar como concluída'}</button>${next?`<a class="button secondary" href="#aula/${next.id}">Próxima aula →</a>`:'<a class="button secondary" href="#progresso">Ver meu progresso</a>'}</div></article><aside class="lesson-aside"><h3>Construa junto</h3><p>Baixe o material e complete o exercício desta aula.</p><a href="${l.material}" download class="button secondary">Baixar material</a><p>Videoaula em preparação. Este caderno traz a explicação, a prática e a entrega planejadas para a aula.</p></aside></div>`;}
  let skillItems=[],skillsError='',skillLimit=60;
  const platformLabel={claude:'Claude · web e aplicativo','claude-code':'Claude Code',codex:'Codex',catalog:'Catálogo · consultar requisitos'};
  function skillCards(items){return items.slice(0,skillLimit).map(s=>`<article class="skill-card"><span class="kicker">${escape(s.category)} · ${escape(platformLabel[s.platform]||s.platform)}</span><h3>${escape(s.title)}</h3><p>${escape(s.description)}</p><p class="note">Versão ${escape(s.version)} · Atualizada em ${new Date(s.updated*1000).toLocaleDateString('pt-BR')}</p><div class="skill-actions">${s.download_url?`<a class="button" href="${escape(s.download_url)}" target="_blank" rel="noopener noreferrer">${s.download_url.startsWith('/api/skills/')?(s.platform==='claude'?'Baixar ZIP para Claude':'Baixar ZIP da skill'):'Abrir pacote'} ↗</a>`:''}${s.source_url?`<a class="text-link" href="${escape(s.source_url)}" target="_blank" rel="noopener noreferrer">Ver fonte ↗</a>`:''}</div>${s.platform==='catalog'?'<p class="note">Entrada do catálogo. Consulte a fonte para conferir instalação e compatibilidade.</p>':s.platform!=='claude'?'<p class="note">Pacote para ferramentas de desenvolvimento. Consulte o SKILL.md e os requisitos; pode exigir MCP, terminal ou outros serviços.</p>':''}${s.install_command?`<details><summary>Comando de instalação</summary><pre>${escape(s.install_command)}</pre><button class="button secondary" data-skill-copy="${s.id}">Copiar comando</button><p class="note">Use no terminal da ferramenta indicada. Este comando não instala a skill no Claude web.</p></details>`:''}</article>`).join('');}
  function skillLibrary(){return `<h1>Biblioteca de Skills.</h1><p class="lede">Sua Central integrada à formação: catálogo por categoria e pacotes do acervo do professor.</p><section class="skills-guide"><h2>Como instalar no seu Claude</h2><ol><li>Escolha uma skill identificada como <b>Claude · web e aplicativo</b> e baixe o pacote ZIP.</li><li>No Claude, abra <b>Customize → Skills</b>, clique em <b>+ → Create skill → Upload a skill</b> e selecione o ZIP.</li><li>Ative a skill e teste com uma tarefa simples. Se a seção não aparecer, confira a execução de código e criação de arquivos em Settings → Capabilities e as permissões da sua organização.</li></ol><p class="note">Skills para Claude Code ou Codex seguem o comando ou pacote indicado no cartão. Confira os arquivos e as instruções antes de instalar.</p><a class="text-link" href="https://support.claude.com/en/articles/12512180-use-skills-in-claude" target="_blank" rel="noopener noreferrer">Guia oficial do Claude ↗</a></section>${skillsError?`<p role="alert" class="note">${escape(skillsError)}</p><button class="button secondary" id="skills-retry">Tentar carregar as skills</button>`:''}<div class="skills-filters"><label>Buscar skill<input id="skill-search" type="search" placeholder="Nome, assunto ou profissão"></label><label>Categoria<select id="skill-category"><option value="">Todas</option>${[...new Set(skillItems.map(s=>s.category))].sort().map(c=>`<option>${escape(c)}</option>`).join('')}</select></label><label>Ferramenta<select id="skill-platform"><option value="">Todas</option>${Object.entries(platformLabel).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label></div><p id="skill-count" class="note" role="status">${skillItems.length} skills disponíveis · até 60 resultados por busca</p><div id="skill-results" class="skills-grid">${skillCards(skillItems)||'<p class="empty-state">O professor ainda não publicou skills nesta biblioteca.</p>'}</div><button class="button secondary" id="skills-more" ${skillItems.length<=skillLimit?'hidden':''}>Mostrar mais skills</button><details class="module"><summary>Prompts e materiais da formação</summary>${materials(true).replace('<h1>Skills e prompts</h1>','')}</details>`;}
  function filterSkills(reset=true){if(reset)skillLimit=60;const term=document.getElementById('skill-search').value.toLocaleLowerCase('pt-BR'),category=document.getElementById('skill-category').value,platform=document.getElementById('skill-platform').value;const filtered=skillItems.filter(s=>(!category||s.category===category)&&(!platform||s.platform===platform)&&[s.title,s.description,s.category].join(' ').toLocaleLowerCase('pt-BR').includes(term));document.getElementById('skill-results').innerHTML=skillCards(filtered)||'<p class="empty-state">Nenhuma skill encontrada com esses filtros.</p>';document.getElementById('skill-count').textContent=`${filtered.length} de ${skillItems.length} skills · exibindo ${Math.min(filtered.length,skillLimit)}`;document.getElementById('skills-more').hidden=filtered.length<=skillLimit;} 
  main.addEventListener('input',e=>{if(['skill-search','skill-category','skill-platform'].includes(e.target.id))filterSkills();});
  main.addEventListener('click',async e=>{const b=e.target.closest('[data-skill-copy]');if(b){const s=skillItems.find(s=>s.id===Number(b.dataset.skillCopy));try{await navigator.clipboard.writeText(s.install_command);notice('Comando copiado.');}catch{notice('Não foi possível copiar. Selecione o comando acima.');}}if(e.target.id==='skills-more'){skillLimit+=60;filterSkills(false);}if(e.target.id==='skills-retry'){e.target.disabled=true;await loadSkills();render(false);}});
  async function loadSkills(){try{skillItems=(await api('api/skills')).skills;skillsError='';}catch(err){skillsError='Não foi possível carregar a biblioteca. '+err.message;}}
  function materials(skills=false){const list=catalog.materials.filter(m=>!skills||['Skill','Prompt'].includes(m.type));return `<h1>${skills?'Skills e prompts':'Materiais para construir.'}</h1><p class="lede">${skills?'Modelos adaptáveis para a sua rotina.':'Roteiros e materiais para construir junto.'}</p><p class="note">Materiais piloto em formato de texto. Revise e adapte à sua realidade antes de utilizar.</p><ul class="list">${list.map(m=>`<li class="material-row"><div><span class="kicker">${escape(m.type)}</span><h3>${escape(m.title)}</h3><p>${escape(m.description)}</p></div><a class="text-link" href="${m.path}" download>Baixar material ↓</a></li>`).join('')}</ul>`;}
  function progress(){const total=pilots().length,done=pilots().filter(l=>completed.has(l.id)).length;return `<h1>Seu progresso, passo a passo.</h1><p class="lede">Acompanhe o que você já construiu.</p><section class="progress-summary"><span class="progress-number">${Math.round(done/total*100)}%</span><div><h3>${done} de ${total} cadernos de aula concluídos</h3><p class="note">${preview?'Nesta prévia, o progresso fica neste navegador.':'Seu progresso está vinculado à sua conta.'}</p><progress value="${done}" max="${total}" aria-label="Cadernos de aula concluídos"></progress></div></section><ul class="list">${pilots().map(l=>`<li class="material-row"><div><h3>${escape(l.title)}</h3><p>${completed.has(l.id)?'Concluída':'Ainda não concluída'}</p></div><a class="text-link" href="#aula/${l.id}">Revisar aula →</a></li>`).join('')}</ul><p class="empty-state">Este registro acompanha o estudo do conteúdo escrito. O certificado de conclusão é emitido pelo professor com a carga horária cursada. Este registro acompanha o estudo escrito e não substitui as aulas ao vivo.</p>`;}
  function render(focus=true){const [view,id]=location.hash.slice(1).split('/');const active=view||'visao';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===(['curso','aula'].includes(active)?'cursos':active))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const screens={visao:overview,cursos:()=>`<h1>Meus cursos</h1><p class="lede">Do primeiro problema à sua própria solução.</p>${courseRows()}`,materiais:()=>materials(),skills:skillLibrary,progresso:progress,curso:()=>course(id),aula:()=>lesson(id)};main.innerHTML=(screens[active]||(()=>empty('Página não encontrada.')))();document.title=`${main.querySelector('h1')?.textContent||'Área do aluno'} | Luís Fernando`;if(focus){main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
  main.addEventListener('click',async e=>{const button=e.target.closest('[data-complete]');if(!button)return;const id=button.dataset.complete;if(!pilots().some(l=>l.id===id))return;const done=!completed.has(id);button.disabled=true;try{if(!preview)await api('api/progress','PUT',{lesson:id,completed:done});if(done)completed.add(id);else completed.delete(id);if(preview){try{localStorage.setItem('lf-preview-progress',JSON.stringify([...completed]));}catch{storageAvailable=false;}}render(false);main.querySelector('[data-complete]')?.focus();notice(storageAvailable?(done?'Aula marcada como concluída.':'Conclusão desmarcada.'):'Progresso atualizado nesta sessão. O navegador não permitiu salvar.');}catch(err){notice(err.message);button.disabled=false;}});
  window.addEventListener('hashchange',()=>catalog&&render());
  async function start(){try{const session=await api('api/session');if(!session.authenticated){location.assign('entrar.html');return;}csrf=session.csrf;const response=await fetch('catalogo.json?v=portfolio-20261002');if(!response.ok)throw new Error('Não foi possível carregar os cursos.');catalog=await response.json();if(preview){try{const saved=JSON.parse(localStorage.getItem('lf-preview-progress')||'[]');completed=new Set(Array.isArray(saved)?saved.filter(id=>pilots().some(l=>l.id===id)):[]);lastLesson=localStorage.getItem('lf-preview-last')||lastLesson;}catch{storageAvailable=false;}}else{const session=await api('api/session');if(!session.authenticated){location.assign('entrar.html');return;}csrf=session.csrf;document.getElementById('mode-label').textContent=`${session.user.name} · Minha formação`;document.getElementById('logout').hidden=false;completed=new Set((await api('api/progress')).completed);}await loadSkills();render(false);}catch(err){main.innerHTML='<h1>Não foi possível abrir sua formação.</h1><p class="lede"></p><button class="button" id="retry">Tentar novamente</button>';main.querySelector('.lede').textContent=err.message;main.querySelector('#retry').onclick=start;}}
  document.getElementById('logout').addEventListener('click',async()=>{try{await api('api/logout','POST',{});location.assign('entrar.html');}catch(err){notice(err.message);}});
  start();
})();



