'use strict';
(() => {
  const preview=document.documentElement.dataset.preview==='true';
  const main=document.getElementById('student-main');
  let catalog,completed=new Set(),csrf='',storageAvailable=true,lastLesson='problema-real';
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const allLessons=()=>catalog.courses.flatMap(c=>c.modules.flatMap(m=>m.lessons));
  const pilots=()=>allLessons().filter(l=>l.available);
  const notice=message=>{const node=document.getElementById('notice');node.textContent=message;clearTimeout(notice.timer);notice.timer=setTimeout(()=>node.textContent='',4500);};
  async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify({...body,csrf})}:{})});if(response.status===401){location.assign('entrar.html');throw new Error('Sua sessão expirou.');}const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível salvar.');return data;}
  function courseRows(){return catalog.courses.map(c=>`<article class="course-row"><div><h3>${escape(c.name)}</h3><p>${escape(c.description)}</p></div><div class="course-status">${escape(c.status)}</div>${c.id==='basica'?`<a class="text-link" href="#curso/${c.id}">Explorar curso <span aria-hidden="true">→</span></a>`:'<span class="note">Aulas em preparação</span>'}</article>`).join('');}
  function overview(){const lesson=pilots().find(l=>l.id===lastLesson&&!completed.has(l.id))||pilots().find(l=>!completed.has(l.id))||pilots()[0];return `<h1>Seu próximo passo começa aqui.</h1><p class="lede">Aprenda, construa e aplique no seu trabalho.</p><section class="continue"><div><span class="kicker">FORMAÇÃO BÁSICA</span><h2>${escape(lesson.title)}</h2><p>Organize sua primeira tarefa com IA.</p><a class="button" href="#aula/${lesson.id}">Abrir aula <span aria-hidden="true">→</span></a></div><span class="big-number" aria-hidden="true">${String(pilots().indexOf(lesson)+1).padStart(2,'0')}</span></section><section><h2>Suas formações</h2>${courseRows()}</section><section class="library-strip"><div><h2>Biblioteca prática</h2><p>Roteiros e materiais para construir junto.</p></div><a href="#materiais" class="text-link">Ver materiais <span aria-hidden="true">→</span></a></section>`;}
  function course(id){const c=catalog.courses.find(c=>c.id===id);if(!c)return empty('Curso não encontrado.');const ready=c.modules.flatMap(m=>m.lessons).filter(l=>l.available);return `<a class="back-link" href="#cursos">← Meus cursos</a><h1>${escape(c.name)}</h1><p class="lede">${escape(c.description)}</p><p class="note">Conteúdo piloto: ${ready.length} leituras guiadas disponíveis. Videoaulas e demais aulas em preparação.</p>${c.modules.map((m,i)=>`<details class="module" ${i===0?'open':''}><summary>${escape(m.name)}</summary>${m.lessons.map(l=>`<div class="lesson-row"><div>${escape(l.title)}<small>${completed.has(l.id)?'Concluída':l.available?'Leitura guiada · conteúdo piloto':'Em preparação'}</small></div>${l.available?`<a class="text-link" href="#aula/${l.id}">Abrir aula →</a>`:'<span class="note">Em breve</span>'}</div>`).join('')}</details>`).join('')}`;}
  const empty=text=>`<h1>${escape(text)}</h1><a class="text-link" href="#visao">Voltar à visão geral</a>`;
  function lesson(id){const l=allLessons().find(l=>l.id===id&&l.available);if(!l)return empty('Esta aula ainda não está disponível.');lastLesson=id;if(preview){try{localStorage.setItem('lf-preview-last',id);}catch{storageAvailable=false;}}const index=pilots().indexOf(l),next=pilots()[index+1];return `<a class="back-link" href="#curso/basica">← Formação Básica</a><h1>${escape(l.title)}</h1><p class="lede">Leitura guiada · conteúdo piloto</p><div class="lesson-layout"><article class="lesson-content">${l.sections.map(s=>`<section><h2>${escape(s.title)}</h2>${s.text?`<p>${escape(s.text)}</p>`:''}${s.steps?`<ol>${s.steps.map(t=>`<li>${escape(t)}</li>`).join('')}</ol>`:''}</section>`).join('')}<div class="completion-actions"><button class="button" data-complete="${id}" aria-pressed="${completed.has(id)}">${completed.has(id)?'Desmarcar conclusão':'Marcar como concluída'}</button>${next?`<a class="button secondary" href="#aula/${next.id}">Próxima aula →</a>`:'<a class="button secondary" href="#progresso">Ver meu progresso</a>'}</div></article><aside class="lesson-aside"><h3>Construa junto</h3><p>Baixe o material e complete o exercício desta aula.</p><a href="${l.material}" download class="button secondary">Baixar material</a><p>Videoaula em preparação. Esta versão contém uma leitura guiada.</p></aside></div>`;}
  function materials(skills=false){const list=catalog.materials.filter(m=>!skills||['Skill','Prompt'].includes(m.type));return `<h1>${skills?'Skills e prompts':'Materiais para construir.'}</h1><p class="lede">${skills?'Modelos adaptáveis para a sua rotina.':'Roteiros e materiais para construir junto.'}</p><p class="note">Materiais piloto em formato de texto. Revise e adapte à sua realidade antes de utilizar.</p><ul class="list">${list.map(m=>`<li class="material-row"><div><span class="kicker">${escape(m.type)}</span><h3>${escape(m.title)}</h3><p>${escape(m.description)}</p></div><a class="text-link" href="${m.path}" download>Baixar material ↓</a></li>`).join('')}</ul>`;}
  function progress(){const total=pilots().length,done=pilots().filter(l=>completed.has(l.id)).length;return `<h1>Seu progresso, passo a passo.</h1><p class="lede">Acompanhe o que você já construiu.</p><section class="progress-summary"><span class="progress-number">${Math.round(done/total*100)}%</span><div><h3>${done} de ${total} aulas piloto concluídas</h3><p class="note">${preview?'Nesta prévia, o progresso fica neste navegador.':'Seu progresso está vinculado à sua conta.'}</p><progress value="${done}" max="${total}" aria-label="Aulas piloto concluídas"></progress></div></section><ul class="list">${pilots().map(l=>`<li class="material-row"><div><h3>${escape(l.title)}</h3><p>${completed.has(l.id)?'Concluída':'Ainda não concluída'}</p></div><a class="text-link" href="#aula/${l.id}">Revisar aula →</a></li>`).join('')}</ul><p class="empty-state">Certificados serão disponibilizados quando a formação completa e os critérios de conclusão estiverem definidos.</p>`;}
  function render(focus=true){const [view,id]=location.hash.slice(1).split('/');const active=view||'visao';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===(['curso','aula'].includes(active)?'cursos':active))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const screens={visao:overview,cursos:()=>`<h1>Meus cursos</h1><p class="lede">Do primeiro problema à sua própria solução.</p>${courseRows()}`,materiais:()=>materials(),skills:()=>materials(true),progresso:progress,curso:()=>course(id),aula:()=>lesson(id)};main.innerHTML=(screens[active]||(()=>empty('Página não encontrada.')))();document.title=`${main.querySelector('h1')?.textContent||'Área do aluno'} | Luís Fernando`;if(focus){main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
  main.addEventListener('click',async e=>{const button=e.target.closest('[data-complete]');if(!button)return;const id=button.dataset.complete;if(!pilots().some(l=>l.id===id))return;const done=!completed.has(id);button.disabled=true;try{if(!preview)await api('api/progress','PUT',{lesson:id,completed:done});if(done)completed.add(id);else completed.delete(id);if(preview){try{localStorage.setItem('lf-preview-progress',JSON.stringify([...completed]));}catch{storageAvailable=false;}}render(false);main.querySelector('[data-complete]')?.focus();notice(storageAvailable?(done?'Aula marcada como concluída.':'Conclusão desmarcada.'):'Progresso atualizado nesta sessão. O navegador não permitiu salvar.');}catch(err){notice(err.message);button.disabled=false;}});
  window.addEventListener('hashchange',()=>catalog&&render());
  async function start(){try{const response=await fetch('catalogo.json?v=1');if(!response.ok)throw new Error('Não foi possível carregar os cursos.');catalog=await response.json();if(preview){try{const saved=JSON.parse(localStorage.getItem('lf-preview-progress')||'[]');completed=new Set(Array.isArray(saved)?saved.filter(id=>pilots().some(l=>l.id===id)):[]);lastLesson=localStorage.getItem('lf-preview-last')||lastLesson;}catch{storageAvailable=false;}}else{const session=await api('api/session');if(!session.authenticated){location.assign('entrar.html');return;}csrf=session.csrf;document.getElementById('mode-label').textContent=`${session.user.name} · Conteúdos piloto`;document.getElementById('logout').hidden=false;completed=new Set((await api('api/progress')).completed);}render(false);}catch(err){main.innerHTML='<h1>Não foi possível abrir sua formação.</h1><p class="lede"></p><button class="button" id="retry">Tentar novamente</button>';main.querySelector('.lede').textContent=err.message;main.querySelector('#retry').onclick=start;}}
  document.getElementById('logout').addEventListener('click',async()=>{try{await api('api/logout','POST',{});location.assign('entrar.html');}catch(err){notice(err.message);}});
  start();
})();
