'use strict';
(() => {
  const preview=document.documentElement.dataset.preview==='true';
  const main=document.getElementById('student-main');
  let catalog,completed=new Set(),csrf='',storageAvailable=true,lastLesson='ia-generativa';
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const allLessons=()=>catalog.courses.flatMap(c=>c.modules.flatMap(m=>m.lessons));
  const pilots=()=>allLessons().filter(l=>l.available);
  const notice=message=>{const node=document.getElementById('notice');node.textContent=message;clearTimeout(notice.timer);notice.timer=setTimeout(()=>node.textContent='',4500);};
  async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify({...body,csrf})}:{})});if(response.status===401){location.assign('entrar.html');throw new Error('Sua sessão expirou.');}let data;try{data=await response.json();}catch{location.assign('entrar.html');throw new Error('Acesso aguardando ativação.');}if(!response.ok)throw new Error(data.error||'Não foi possível salvar.');return data;}
  function courseRows(){return catalog.courses.map(c=>`<article class="course-row"><div><h3>${escape(c.name)}</h3><p>${escape(c.description)}</p></div><div class="course-status">${escape(c.status)}</div><a class="text-link" href="#curso/${c.id}">Explorar jornada <span aria-hidden="true">→</span></a></article>`).join('');}
  function overview(){const lesson=pilots().find(l=>l.id===lastLesson&&!completed.has(l.id))||pilots().find(l=>!completed.has(l.id))||pilots()[0];return `<h1>Seu próximo passo começa aqui.</h1><p class="lede">Aprenda, construa e aplique no seu trabalho.</p><section class="continue"><div><span class="kicker">CADERNO DE AULA · JORNADA ESCRITA</span><h2>${escape(lesson.title)}</h2><p>Leia, pratique e registre sua entrega.</p><a class="button" href="#aula/${lesson.id}">Abrir aula <span aria-hidden="true">→</span></a></div><span class="big-number" aria-hidden="true">${String(pilots().indexOf(lesson)+1).padStart(2,'0')}</span></section><section><h2>Suas formações</h2>${courseRows()}</section><section class="library-strip"><div><h2>Biblioteca prática</h2><p>Roteiros e materiais para construir junto.</p></div><a href="#materiais" class="text-link">Ver materiais <span aria-hidden="true">→</span></a></section>`;}
  function course(id){const c=catalog.courses.find(c=>c.id===id);if(!c)return empty('Curso não encontrado.');const ready=c.modules.flatMap(m=>m.lessons).filter(l=>l.available);return `<a class="back-link" href="#cursos">← Meus cursos</a><h1>${escape(c.name)}</h1><p class="lede">${escape(c.description)}</p><p class="note">${c.hours} horas ao vivo pelo Google Meet · ${ready.length} cadernos de aula disponíveis. Videoaulas em preparação. <a class="text-link" href="planos.html#${c.id}">Ver planejamento completo →</a></p>${c.modules.map((m,i)=>`<details class="module" ${i===0?'open':''}><summary>${escape(m.name)}</summary>${m.lessons.map(l=>`<div class="lesson-row"><div>${escape(l.title)}<small>${completed.has(l.id)?'Concluída':l.available?'Caderno de aula · vídeo em preparação':'Em preparação'}</small></div>${l.available?`<a class="text-link" href="#aula/${l.id}">Abrir aula →</a>`:'<span class="note">Em breve</span>'}</div>`).join('')}</details>`).join('')}`;}
  const empty=text=>`<h1>${escape(text)}</h1><a class="text-link" href="#visao">Voltar à visão geral</a>`;
  function lesson(id){const l=allLessons().find(l=>l.id===id&&l.available);if(!l)return empty('Esta aula ainda não está disponível.');lastLesson=id;if(preview){try{localStorage.setItem('lf-preview-last',id);}catch{storageAvailable=false;}}const owner=catalog.courses.find(c=>c.modules.some(m=>m.lessons.some(x=>x.id===id)));const sequence=owner.modules.flatMap(m=>m.lessons).filter(x=>x.available);const index=sequence.indexOf(l),next=sequence[index+1];return `<a class="back-link" href="#curso/${owner.id}">← ${escape(owner.name)}</a><h1>${escape(l.title)}</h1><p class="lede">Caderno escrito · módulo ao vivo pelo Google Meet · ${l.duration} min</p><div class="lesson-layout"><article class="lesson-content">${l.sections.map(s=>`<section><h2>${escape(s.title)}</h2>${s.text?`<p>${escape(s.text)}</p>`:''}${s.steps?`<ol>${s.steps.map(t=>`<li>${escape(t)}</li>`).join('')}</ol>`:''}</section>`).join('')}<div class="completion-actions"><button class="button" data-complete="${id}" aria-pressed="${completed.has(id)}">${completed.has(id)?'Desmarcar conclusão':'Marcar como concluída'}</button>${next?`<a class="button secondary" href="#aula/${next.id}">Próxima aula →</a>`:'<a class="button secondary" href="#progresso">Ver meu progresso</a>'}</div></article><aside class="lesson-aside"><h3>Construa junto</h3><p>Baixe o material e complete o exercício desta aula.</p><a href="${l.material}" download class="button secondary">Baixar material</a><p>Videoaula em preparação. Este caderno traz a explicação, a prática e a entrega planejadas para a aula.</p></aside></div>`;}
  let skillItems=[],skillsError='',skillLimit=60,skillCategory='',skillTrigger;
  const platformLabel={claude:'Claude · web e aplicativo','claude-code':'Claude Code',codex:'Codex',catalog:'Consultar compatibilidade'};
  const skillUrl=value=>{if(typeof value!=='string')return '';if(/^\/api\/skills\/[0-9]+\/download$/.test(value))return value;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
  const skillDialog=document.createElement('dialog');skillDialog.id='skill-dialog';skillDialog.className='skill-dialog';skillDialog.setAttribute('aria-labelledby','skill-dialog-title');document.body.append(skillDialog);
  skillDialog.addEventListener('close',()=>{if(skillTrigger?.isConnected)skillTrigger.focus();else main.focus({preventScroll:true});});
  skillDialog.addEventListener('click',e=>{if(e.target===skillDialog){const r=skillDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)skillDialog.close();}});
  function skillCards(items){return items.slice(0,skillLimit).map(s=>{const source=skillUrl(s.source_url),pack=skillUrl(s.download_url);return `<article class="skill-card"><div class="skill-card-top"><span class="skill-symbol" aria-hidden="true">✧</span><span class="skill-badge ${pack?'has-package':''}">${pack?'Pacote disponível':'Fonte externa'}</span></div><p class="skill-category">${escape(s.category)}</p><h3>${escape(s.title)}</h3><p class="skill-version">${escape(s.version)}</p><p class="skill-description">${escape(s.description.replace(/^>\s*/,''))}</p><p class="skill-compatibility">${escape(platformLabel[s.platform]||s.platform)}</p><div class="skill-actions"><button class="button" data-skill-open="${s.id}">${pack?'Instalar':'Ver instruções'}</button>${source?`<a class="skill-source" href="${escape(source)}" target="_blank" rel="noopener noreferrer" aria-label="Ver fonte de ${escape(s.title)}">↗</a>`:''}</div></article>`;}).join('');}
  function skillLibrary(){const preferred=['Finanças e BI','Marketing','Automação n8n','Produtividade e Colaboração','Skills Essenciais','Desenvolvimento e Testes','Skills Oficiais do Claude','Skills próprias'];const rank=c=>preferred.includes(c)?preferred.indexOf(c):preferred.length;const categories=[...new Set(skillItems.map(s=>s.category))].sort((a,b)=>rank(a)-rank(b)||a.localeCompare(b,'pt-BR'));return `<section class="skills-heading"><p class="kicker">BIBLIOTECA DE SKILLS</p><h1>Habilidades prontas<br><em>para o seu próximo projeto.</em></h1><p class="lede">Escolha uma skill e leve o conhecimento da formação para o Claude ou o Codex.</p></section>${skillsError?`<p role="alert" class="note">${escape(skillsError)}</p><button class="button secondary" id="skills-retry">Tentar carregar as skills</button>`:''}<div class="skills-toolbar"><label class="skill-search-field"><span class="sr-only">Buscar skill</span><span aria-hidden="true">⌕</span><input id="skill-search" type="search" placeholder="Buscar skill, assunto ou profissão"></label><label class="skill-tool-field"><span class="sr-only">Ferramenta</span><select id="skill-platform"><option value="">Todas as ferramentas</option>${Object.entries(platformLabel).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><label class="skill-tool-field"><span class="sr-only">Categoria</span><select id="skill-category"><option value="">Todas as categorias</option>${categories.map(c=>`<option ${skillCategory===c?'selected':''}>${escape(c)}</option>`).join('')}</select></label><p id="skill-count" role="status">${skillItems.length} skills disponíveis</p></div><div class="skill-categories" role="group" aria-label="Filtrar por categoria"><button type="button" data-skill-category="" aria-pressed="${!skillCategory}">Todas <span>${skillItems.length}</span></button>${[...new Set([...categories.slice(0,8),...(skillCategory?[skillCategory]:[])])].map(c=>`<button type="button" data-skill-category="${escape(c)}" aria-pressed="${skillCategory===c}">${escape(c)} <span>${skillItems.filter(s=>s.category===c).length}</span></button>`).join('')}</div><div id="skill-results" class="skills-grid">${skillCards(skillItems)||'<p class="empty-state">O professor ainda não publicou skills nesta biblioteca.</p>'}</div><button class="button secondary" id="skills-more" ${skillItems.length<=skillLimit?'hidden':''}>Mostrar mais skills</button><details class="module skills-help"><summary>Como usar as skills e os materiais da formação</summary><p class="note">Abra as instruções de uma skill para baixar o pacote ou consultar sua fonte. A instalação depende da ferramenta e dos requisitos indicados; copiar o prompt não instala a skill automaticamente.</p>${materials(true).replace('<h1>Skills e prompts</h1>','')}</details>`;}
  function filterSkills(reset=true){if(reset)skillLimit=60;const term=document.getElementById('skill-search').value.toLocaleLowerCase('pt-BR'),platform=document.getElementById('skill-platform').value;const filtered=skillItems.filter(s=>(!skillCategory||s.category===skillCategory)&&(!platform||s.platform===platform)&&[s.title,s.description,s.category].join(' ').toLocaleLowerCase('pt-BR').includes(term));document.getElementById('skill-results').innerHTML=skillCards(filtered)||'<p class="empty-state">Nenhuma skill encontrada com esses filtros.</p>';document.getElementById('skill-count').textContent=`${filtered.length} skills · ${Math.min(filtered.length,skillLimit)} exibidas`;document.getElementById('skills-more').hidden=filtered.length<=skillLimit;document.getElementById('skill-category').value=skillCategory;main.querySelectorAll('[data-skill-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.skillCategory===skillCategory)));}
  function openSkill(id,trigger){const s=skillItems.find(s=>String(s.id)===id);if(!s)return;skillTrigger=trigger;const pack=skillUrl(s.download_url),source=skillUrl(s.source_url),web=s.platform==='claude';const context=pack?'O pacote ZIP desta skill está anexado à conversa.':'A fonte desta skill é: '+(source||'solicite o pacote ao professor')+'.';const prompt=tool=>`Quero instalar e usar a skill "${s.title}" no ${tool}.\n${context}\n${s.description}\nLeia o SKILL.md e confira a compatibilidade e os requisitos. ${tool==='Claude'?'Depois de ativada nas configurações do Claude, explique como usar esta skill com uma tarefa prática.':'Se for compatível, instale no projeto atual, preserve as configurações existentes e confirme os arquivos criados. Explique como testar com uma tarefa prática.'} Se precisar de arquivos, acesso ou configuração adicional, me informe antes de continuar.${s.install_command?'\nComando informado pelo professor (confira antes de executar):\n'+s.install_command:''}`;
   skillDialog.innerHTML=`<header class="skill-dialog-header"><div><p class="kicker">BIBLIOTECA · LUÍS FERNANDO</p><h2 id="skill-dialog-title">${escape(s.title)}</h2><p>${escape(s.category)} · ${escape(s.version)}</p></div><button type="button" class="skill-close" aria-label="Fechar instruções">×</button></header><div class="skill-dialog-content"><p class="skill-dialog-description">${escape(s.description.replace(/^>\s*/,''))}</p><h3>Instale no seu agente</h3>${pack?`<div class="skill-download"><a class="button" href="${escape(pack)}" target="_blank" rel="noopener noreferrer">${web?'Baixar ZIP para Claude':'Baixar ZIP da skill'} ↗</a><p>Baixe o pacote e anexe à conversa antes de usar o prompt.</p></div>`:'<p class="note">Esta entrada tem uma fonte externa. Consulte a documentação para obter o pacote e conferir os requisitos.</p>'}<section class="skill-install-section"><h4>${web?'Instalar no Claude':'Usar no Claude Code'}</h4><p>${web?'No Claude, abra Customize → Skills e envie o ZIP em Upload a skill. Depois, ative a skill.':'Abra seu projeto no Claude Code. Anexe ou disponibilize o pacote e use o prompt para conferir a instalação.'}</p><label class="sr-only" for="skill-prompt-claude">Prompt para Claude</label><textarea id="skill-prompt-claude" readonly spellcheck="false">${escape(prompt(web?'Claude':'Claude Code'))}</textarea><button class="button" type="button" data-copy-prompt="skill-prompt-claude">Copiar prompt (Claude)</button></section><section class="skill-install-section codex"><h4>Usar no ChatGPT / Codex</h4><p>Abra seu projeto no Codex, disponibilize o pacote e cole o prompt. A instalação será conferida conforme a compatibilidade da skill.</p><label class="sr-only" for="skill-prompt-codex">Prompt para Codex</label><textarea id="skill-prompt-codex" readonly spellcheck="false">${escape(prompt('Codex'))}</textarea><button class="button" type="button" data-copy-prompt="skill-prompt-codex">Copiar prompt (Codex)</button></section><p id="skill-copy-status" role="status" aria-live="polite"></p><footer class="skill-dialog-footer"><span>${escape(platformLabel[s.platform]||s.platform)}</span>${source?`<a class="text-link" href="${escape(source)}" target="_blank" rel="noopener noreferrer">Ver fonte ↗</a>`:''}</footer></div>`;
   skillDialog.querySelector('.skill-close').onclick=()=>skillDialog.close();skillDialog.showModal();skillDialog.querySelector('.skill-close').focus();
  }
  skillDialog.addEventListener('click',async e=>{const b=e.target.closest('[data-copy-prompt]');if(!b)return;const field=document.getElementById(b.dataset.copyPrompt),status=document.getElementById('skill-copy-status');try{await navigator.clipboard.writeText(field.value);status.textContent='Prompt copiado. Cole na ferramenta indicada.';}catch{field.focus();field.select();status.textContent='Selecionei o prompt. Copie com o menu do navegador ou Ctrl+C.';}});
  main.addEventListener('input',e=>{if(e.target.id==='skill-category'){skillCategory=e.target.value;filterSkills();}else if(['skill-search','skill-platform'].includes(e.target.id))filterSkills();});
  main.addEventListener('click',async e=>{const open=e.target.closest('[data-skill-open]'),category=e.target.closest('[data-skill-category]');if(open)openSkill(open.dataset.skillOpen,open);if(category){skillCategory=category.dataset.skillCategory;filterSkills();}if(e.target.id==='skills-more'){skillLimit+=60;filterSkills(false);}if(e.target.id==='skills-retry'){e.target.disabled=true;await loadSkills();render(false);filterSkills();}});
  async function loadSkills(){try{skillItems=(await api('api/skills')).skills.sort((a,b)=>Number(!!skillUrl(b.download_url))-Number(!!skillUrl(a.download_url))||a.title.localeCompare(b.title,'pt-BR'));skillsError='';}catch(err){skillsError='Não foi possível carregar a biblioteca. '+err.message;}}
  function materials(skills=false){const list=catalog.materials.filter(m=>!skills||['Skill','Prompt'].includes(m.type));return `<h1>${skills?'Skills e prompts':'Materiais para construir.'}</h1><p class="lede">${skills?'Modelos adaptáveis para a sua rotina.':'Roteiros e materiais para construir junto.'}</p><p class="note">Materiais piloto em formato de texto. Revise e adapte à sua realidade antes de utilizar.</p><ul class="list">${list.map(m=>`<li class="material-row"><div><span class="kicker">${escape(m.type)}</span><h3>${escape(m.title)}</h3><p>${escape(m.description)}</p></div><a class="text-link" href="${m.path}" download>Baixar material ↓</a></li>`).join('')}</ul>`;}
  function progress(){const total=pilots().length,done=pilots().filter(l=>completed.has(l.id)).length;return `<h1>Seu progresso, passo a passo.</h1><p class="lede">Acompanhe o que você já construiu.</p><section class="progress-summary"><span class="progress-number">${Math.round(done/total*100)}%</span><div><h3>${done} de ${total} cadernos de aula concluídos</h3><p class="note">${preview?'Nesta prévia, o progresso fica neste navegador.':'Seu progresso está vinculado à sua conta.'}</p><progress value="${done}" max="${total}" aria-label="Cadernos de aula concluídos"></progress></div></section><ul class="list">${pilots().map(l=>`<li class="material-row"><div><h3>${escape(l.title)}</h3><p>${completed.has(l.id)?'Concluída':'Ainda não concluída'}</p></div><a class="text-link" href="#aula/${l.id}">Revisar aula →</a></li>`).join('')}</ul><p class="empty-state">Este registro acompanha o estudo do conteúdo escrito. O certificado de conclusão é emitido pelo professor com a carga horária cursada. Este registro acompanha o estudo escrito e não substitui as aulas ao vivo.</p>`;}
  function render(focus=true){const [view,id]=location.hash.slice(1).split('/');const active=view||'visao';document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===(['curso','aula'].includes(active)?'cursos':active))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const screens={visao:overview,cursos:()=>`<h1>Meus cursos</h1><p class="lede">Do primeiro problema à sua própria solução.</p>${courseRows()}`,materiais:()=>materials(),skills:skillLibrary,progresso:progress,curso:()=>course(id),aula:()=>lesson(id)};if(skillDialog.open)skillDialog.close();main.innerHTML=(screens[active]||(()=>empty('Página não encontrada.')))();if(active==='skills')filterSkills();document.title=`${main.querySelector('h1')?.textContent||'Área do aluno'} | Luís Fernando`;if(focus){main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
  main.addEventListener('click',async e=>{const button=e.target.closest('[data-complete]');if(!button)return;const id=button.dataset.complete;if(!pilots().some(l=>l.id===id))return;const done=!completed.has(id);button.disabled=true;try{if(!preview)await api('api/progress','PUT',{lesson:id,completed:done});if(done)completed.add(id);else completed.delete(id);if(preview){try{localStorage.setItem('lf-preview-progress',JSON.stringify([...completed]));}catch{storageAvailable=false;}}render(false);main.querySelector('[data-complete]')?.focus();notice(storageAvailable?(done?'Aula marcada como concluída.':'Conclusão desmarcada.'):'Progresso atualizado nesta sessão. O navegador não permitiu salvar.');}catch(err){notice(err.message);button.disabled=false;}});
  window.addEventListener('hashchange',()=>catalog&&render());
  async function start(){try{const session=await api('api/session');if(!session.authenticated){location.assign('entrar.html');return;}csrf=session.csrf;const response=await fetch('catalogo.json?v=portfolio-20261002');if(!response.ok)throw new Error('Não foi possível carregar os cursos.');catalog=await response.json();if(preview){try{const saved=JSON.parse(localStorage.getItem('lf-preview-progress')||'[]');completed=new Set(Array.isArray(saved)?saved.filter(id=>pilots().some(l=>l.id===id)):[]);lastLesson=localStorage.getItem('lf-preview-last')||lastLesson;}catch{storageAvailable=false;}}else{const session=await api('api/session');if(!session.authenticated){location.assign('entrar.html');return;}csrf=session.csrf;document.getElementById('mode-label').textContent=`${session.user.name} · Minha formação`;document.getElementById('logout').hidden=false;completed=new Set((await api('api/progress')).completed);}await loadSkills();render(false);}catch(err){main.innerHTML='<h1>Não foi possível abrir sua formação.</h1><p class="lede"></p><button class="button" id="retry">Tentar novamente</button>';main.querySelector('.lede').textContent=err.message;main.querySelector('#retry').onclick=start;}}
  document.getElementById('logout').addEventListener('click',async()=>{try{await api('api/logout','POST',{});location.assign('entrar.html');}catch(err){notice(err.message);}});
  start();
})();



