'use strict';
const $=id=>document.getElementById(id),form=$('checkout-form');
const adminTest=new URLSearchParams(location.search).get('teste')==='admin';
const course=adminTest?'admin_test':new URLSearchParams(location.search).get('curso')||'basica';
let adminCsrf='';
const fallback={admin_test:{name:'Teste administrativo de pagamento',amount:100,hours:0,modules:0},basica:{name:'Formação Básica em IA',amount:99700,hours:10,modules:8},avancada:{name:'Formação Avançada em IA',amount:169900,hours:20,modules:10}};
let enabled=false,order=null,pollTimer=null;
function product(c,products=fallback){const p=products[c];if(!p)throw Error('Escolha uma formação na página de planos.');$('product-name').textContent=p.name;$('product-price').textContent=(p.amount/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});$('course-hours').textContent=p.hours+' horas ao vivo';$('course-modules').textContent=p.modules+' módulos';$('product-description').textContent=c==='avancada'?'Construa seu site e seu sistema com dados, automações e IA.':'IA, indicadores e automação para aplicar no seu trabalho.';if($('course-info'))$('course-info').href='planos.html#'+c;}
function notice(message){$('availability').textContent=message;$('availability').hidden=false;}
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});let j;try{j=await r.json();}catch{throw Error('Não foi possível conectar ao serviço de matrícula. Tente novamente.');}if(!r.ok)throw Error(j.error||'Não foi possível concluir agora.');return j;}
function secret(){const bytes=crypto.getRandomValues(new Uint8Array(32));return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
let buyerKey=secret();
const fragment=new URLSearchParams(location.hash.slice(1));
if(/^[a-f0-9]{32}$/.test(fragment.get('pedido')||'')&&/^[a-f0-9]{64}$/.test(fragment.get('chave')||'')){order={reference:fragment.get('pedido'),key:fragment.get('chave')};try{sessionStorage.setItem('lf-payment',JSON.stringify(order));}catch{}history.replaceState(null,'',location.pathname+location.search);}
else if(new URLSearchParams(location.search).has('retorno')){try{order=JSON.parse(sessionStorage.getItem('lf-payment')||'null');}catch{}}
function result(state){const texts={PAID:['Pagamento confirmado!','Sua matrícula está pronta. Continue para acessar seus materiais e combine a agenda das aulas com Luís Fernando.'],IN_ANALYSIS:['Pagamento em análise','O PagBank está analisando o pagamento. Sua matrícula será liberada após a confirmação.'],DECLINED:['Pagamento não aprovado','O pagamento foi recusado. Você pode iniciar uma nova matrícula ou pedir ajuda ao professor.'],REVIEW:['Precisamos conferir seu acesso','Seu pedido exige uma conferência. Fale com Luís Fernando pelo WhatsApp para concluir a liberação.'],WAITING:['Aguardando a confirmação','Se você já pagou, aguarde a confirmação do PagBank. Esta página será atualizada automaticamente.'],CREATING:['Preparando seu pedido','Aguarde enquanto seu pedido é preparado.']};return texts[state]||texts.WAITING;}
function testView(){document.querySelector('h1').textContent='Teste de pagamento de R$ 1,00';form.querySelector('h2').textContent='Seus dados para o teste';form.querySelector('.hint').textContent='O pagamento será informado diretamente no PagBank.';document.querySelector('.consent span').textContent='Entendi que em produção será cobrado R$ 1,00 real e este teste não libera acesso a cursos.';document.querySelector('.payment-options strong small').textContent='À vista pelo PagBank';document.querySelectorAll('.payment-options strong small')[1].textContent='Em 1x';document.querySelector('.course-meta').hidden=true;document.querySelector('.included').hidden=true;document.querySelector('.after-payment').hidden=true;document.querySelector('.order-card > .hint').hidden=true;document.querySelector('.price-note').textContent='Pix ou cartão em 1x. Sem liberação de curso.';$('product-description').textContent='Teste exclusivo do administrador. Valor fixo de R$ 1,00.';}
async function status(){if(!order)return;$('refresh-status').disabled=true;try{const j=await api('/api/payments/status',order);product(j.course,{...fallback,[j.course]:{...fallback[j.course],amount:j.amount??fallback[j.course].amount}});const text=result(j.state);$('result-title').textContent=text[0];$('result-copy').textContent=text[1];if(j.admin_test){testView();$('result-title').textContent=j.state==='PAID'?'Teste confirmado!':text[0];$('result-copy').textContent='Teste administrativo de R$ 1,00. Não há liberação de curso.';}if(j.environment==='sandbox'){$('result-title').textContent=j.state==='PAID'?'Pagamento de teste confirmado!':'Pedido de teste';$('result-copy').textContent='Este pagamento está no ambiente de testes do PagBank. Não há cobrança real nem liberação de curso.';}if(j.access_url&&/^\/(entrar\.html|ativar\.html#[a-f0-9]{64})$/.test(j.access_url)){$('access-link').href=j.access_url;$('access-link').hidden=false;$('refresh-status').hidden=true;}if(['WAITING','IN_ANALYSIS','CREATING'].includes(j.state)&&!document.hidden)pollTimer=setTimeout(status,20000);}catch(e){$('result-copy').textContent=e.message;}finally{$('refresh-status').disabled=false;}}
$('refresh-status').onclick=()=>{clearTimeout(pollTimer);status();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(pollTimer);else if(order)status();});
form.onsubmit=async e=>{e.preventDefault();$('checkout-error').textContent='';if(!enabled){$('checkout-error').textContent='O pagamento online está sendo preparado. Fale com Luís Fernando pelo WhatsApp.';return;}const button=$('pay-button');button.disabled=true;button.textContent='Abrindo pagamento seguro…';try{const f=new FormData(form);const j=await api(adminTest?'/api/admin/payments/test':'/api/payments/create',{...(adminTest?{csrf:adminCsrf}:{}),course,key:buyerKey,name:f.get('name'),email:f.get('email'),cpf:f.get('cpf'),phone:f.get('phone'),accepted:f.get('accepted')==='on'});const url=new URL(j.url);if(url.protocol!=='https:'||!['pagamento.pagbank.com.br','sandbox.pagamento.pagbank.com.br','pagamento.sandbox.pagbank.com.br'].includes(url.hostname)||url.username||url.password||url.port)throw Error('O link de pagamento não pôde ser validado.');order={reference:j.reference,key:buyerKey};try{sessionStorage.setItem('lf-payment',JSON.stringify(order));}catch{}location.assign(url.href);}catch(err){$('checkout-error').textContent=err.message;button.disabled=false;button.textContent='Tentar novamente →';}};
(async()=>{try{product(course);if(order){form.hidden=true;$('payment-result').hidden=false;await status();return;}if(adminTest){testView();const session=await api('/api/session');if(!session.authenticated||session.user.role!=='admin')throw Error('Entre como administrador para acessar o teste de R$ 1,00.');adminCsrf=session.csrf;}const config=await api(adminTest?'/api/admin/payments/test':'/api/payments/config');product(course,config.products);if(adminTest)testView();enabled=config.enabled;if(adminTest&&config.environment==='production')notice('Teste em produção: será cobrado R$ 1,00 real. Cartão em 1x ou Pix.');if(!enabled)notice('As matrículas online estão sendo preparadas. Para contratar agora, converse com Luís Fernando pelo WhatsApp.');else if(config.environment==='sandbox')notice('Ambiente de testes: nenhum pagamento real será cobrado e nenhum curso será liberado.');}catch(e){notice(e.message);}})();
