CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL, email VARCHAR(254) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'student',
 active TINYINT NOT NULL DEFAULT 1, courses TEXT NOT NULL,
 otp_step BIGINT NOT NULL DEFAULT -1, created BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 csrf CHAR(64) NOT NULL, expires BIGINT NOT NULL, last_seen BIGINT NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX session_expiry(expires)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS progress (
 user_id BIGINT UNSIGNED NOT NULL, lesson_id VARCHAR(100) NOT NULL,
 completed TINYINT NOT NULL, updated BIGINT NOT NULL,
 PRIMARY KEY(user_id,lesson_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS access_tokens (
 token_hash CHAR(64) PRIMARY KEY, purpose VARCHAR(16) NOT NULL,
 email VARCHAR(254) NOT NULL, name VARCHAR(120) NOT NULL DEFAULT '',
 courses TEXT NOT NULL, user_id BIGINT UNSIGNED NULL,
 expires BIGINT NOT NULL, used TINYINT NOT NULL DEFAULT 0,
 INDEX token_email(email,purpose), INDEX token_expiry(expires)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS limits (
 key_hash CHAR(64) PRIMARY KEY, window_start BIGINT NOT NULL, count INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor BIGINT UNSIGNED NULL,
 event VARCHAR(40) NOT NULL, target VARCHAR(254) NULL, created BIGINT NOT NULL,
 INDEX audit_created(created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS mail_jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL,
 purpose VARCHAR(16) NOT NULL, token_hash CHAR(64) NULL,
 attempts INT NOT NULL DEFAULT 0, available BIGINT NOT NULL, created BIGINT NOT NULL,
 INDEX mail_due(available)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
